const STORE = {
    id: "Dwu85P9SOIk",
    created_at: "2016-05-03T11:00:28-04:00",
    updated_at: "2016-07-10T11:00:01-05:00",
    width: 2448,
    height: 3264,
    color: "#6E633A",
    blur_hash: "LFC$yHwc8^$yIAS$%M%00KxukYIp",
    downloads: 1345,
    likes: 24,
    liked_by_user: false,
    description: "A man drinking a coffee.",
    exif: {
        make: "Canon",
        model: "Canon EOS 40D",
        exposure_time: "0.011111111111111112",
        aperture: "4.970854",
        focal_length: "37",
        iso: 100,
    },
    location: {
        name: "Montreal, Canada",
        city: "Montreal",
        country: "Canada",
        position: {
            latitude: 45.473298,
            longitude: -73.638488,
        },
    },
    current_user_collections: [
        // The *current user's* collections that this photo belongs to.
        {
            id: 206,
            title: "Makers: Cat and Ben",
            published_at: "2016-01-12T18:16:09-05:00",
            last_collected_at: "2016-06-02T13:10:03-04:00",
            updated_at: "2016-07-10T11:00:01-05:00",
            cover_photo: null,
            user: null,
        },
        // ... more collections
    ],
    urls: {
        raw: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d",
        full: "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg",
        regular:
            "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=1080&fit=max",
        small:
            "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=400&fit=max",
        thumb:
            "https://images.unsplash.com/photo-1417325384643-aac51acc9e5d?q=75&fm=jpg&w=200&fit=max",
    },
    links: {
        self: "https://api.unsplash.com/photos/Dwu85P9SOIk",
        html: "https://unsplash.com/photos/Dwu85P9SOIk",
        download: "https://unsplash.com/photos/Dwu85P9SOIk/download",
        download_location: "https://api.unsplash.com/photos/Dwu85P9SOIk/download",
    },
    user: {
        id: "QPxL2MGqfrw",
        updated_at: "2016-07-10T11:00:01-05:00",
        username: "exampleuser",
        name: "Joe Example",
        portfolio_url: "https://example.com/",
        bio: "Just an everyday Joe",
        location: "Montreal",
        total_likes: 5,
        total_photos: 10,
        total_collections: 13,
        instagram_username: "instantgrammer",
        twitter_username: "crew",
        links: {
            self: "https://api.unsplash.com/users/exampleuser",
            html: "https://unsplash.com/exampleuser",
            photos: "https://api.unsplash.com/users/exampleuser/photos",
            likes: "https://api.unsplash.com/users/exampleuser/likes",
            portfolio: "https://api.unsplash.com/users/exampleuser/portfolio",
        },
    },
};

export const CUSTOM_MESSAGES = {
    1: "New Years Day",
    4: "Back to School",
    30: "Aleigha Birthday",
    113: "Marc Birthday",
    114: "valentines day",
    214: "daylight savings",
    217: "saint patricks",
    31: "april fools day",
    34: "easter",
    37: "donovan birthday",
    317: "husband appreciation day",
    43: "anniversary",
    44: "ass backwards day part 1",
    45: "ass backwards day part 2",
    47: "wife appreciation day",
    49: "mother day",
    431: "memorial day",
    520: "father day",
    62: "i forgot day",
    64: "independence day",
    86: "labor day",
    911: "columbus day",
    931: "halloween",
    1025: "thanksgiving",
    1026: "black friday",
    1122: "chloe birthday",
    1124: "christmas eve",
    1125: "christmas day",
    1131: "new years eve",
};

export const RANDOM_MESSAGES = {
    1: `Love For All, Hatred For None`,
    2: `Change the world by being yourself`,
    3: `Every moment is a fresh beginning`,
    4: `Never regret anything that made you smile`,
    5: `Die with memories, not dreams`,
    6: `Aspire to inspire before we expire`,
    7: `Everything you can imagine is real`,
    8: `Simplicity is the ultimate sophistication`,
    9: `Whatever you do, do it well`,
    10: `What we think, we become`,
    11: `All limitations are self-imposed`,
    12: `Tough times never last but tough people do`,
    13: `Problems are not stop signs, they are guidelines`,
    14: `One day the people that don’t even believe in you will tell everyone how they met you`,
    15: `If I’m gonna tell a real story, I’m gonna start with my name`,
    16: `If you tell the truth you don’t have to remember anything`,
    17: `Have enough courage to start and enough heart to finish`,
    18: `Hate comes from intimidation, love comes from appreciation`,
    19: `I could agree with you but then we’d both be wrong`,
    20: `Oh, the things you can find, if you don’t stay behind`,
    21: `Determine your priorities and focus on them`,
    22: `Be so good they can’t ignore you`,
    23: `Dream as if you’ll live forever, live as if you’ll die today`,
    24: `Yesterday you said tomorrow. Just do it`,
    25: `I don’t need it to be easy, I need it to be worth it`,
    26: `Never let your emotions overpower your intelligence`,
    27: `Nothing lasts forever but at least we got these memories`,
    28: `Don’t you know your imperfections is a blessing?`,
    29: `Reality is wrong, dreams are for real`,
    30: `To live will be an awfully big adventure`,
    31: `Try to be a rainbow in someone’s cloud`,
    32: `There is no substitute for hard work`,
    33: `What consumes your mind controls your life`,
    34: `Strive for greatness`,
    35: `Wanting to be someone else is a waste of who you are`,
    36: `And still, I rise`,
    37: `The time is always right to do what is right`,
    38: `Let the beauty of what you love be what you do`,
    39: `May your choices reflect your hopes, not your fears`,
    40: `A happy soul is the best shield for a cruel world`,
    41: `White is not always light and black is not always dark`,
    42: `Life becomes easier when you learn to accept the apology you never got`,
    43: `Happiness depends upon ourselves`,
    44: `Turn your wounds into wisdom`,
    45: `Change the game, don’t let the game change you`,
    46: `It hurt because it mattered`,
    47: `If the world was blind how many people would you impress?`,
    48: `I will remember and recover, not forgive and forget`,
    49: `The meaning of life is to give life meaning`,
    50: `The true meaning of life is to plant trees, under whose shade you do not expect to sit`,
    51: `When words fail, music speaks`,
    52: `Embrace the glorious mess that you are`,
    53: `Normality is a paved road: it’s comfortable to walk but no flowers grow`,
    54: `I have nothing to lose but something to gain`,
};

export const SAYINGS = {
    1: "Eat tons of junk food, watch a movie, and play a game.",
    2: "Sky High-Indoor Trampolines",
    3: "Take Mom and Dad to Dinner",
    4: "Go to the Movies",
    5: "Bake cookies and watch a movie",
    6: "Go to the Airport and watch Planes Come & Go",
    7: "Go Roller Skating",
    8: "Go to the Park",
    9: "Go to the Drive-In",
    10: "Just Do it",
    11: "Get a group together to play volleyball",
    12: "Play Laser Tag",
    13: "Play Twister",
    14: "Take a picnic to the park",
    15: "Go Kayaking",
    16: "Go Hiking",
    17: "Go Bike Riding",
    18: "Go try on clothes",
    19: "Play Putt-Putt",
    20: "Prank Call People",
    21: "Play Dress Up",
    22: "Marc Cook's Dinner",
    23: "Buy a new toy",
    24: "Fancy Dinner",
    25: "Lock the Doors and oil up",
    26: "Lady's Choice",
    27: "Go Bowling",
    28: "Build a fort",
    29: "Get a Back Rub",
    30: "Bake a cake",
    31: "Role Play",
    32: "She does whatever he says",
    33: "He does whatever she says",
    34: "Hot Bath",
};
